services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_bridge
    restart: unless-stopped

networks:
  caddy_bridge:
    driver: bridge
    enable_ipv6: true

volumes:
  caddy_data:
  caddy_config:
